### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lzzqwe** [maomao1996/react-music#9]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at noopServiceWorkerMiddleware (E:\react学习\react-music\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (E:\react学习\react-music\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\react学习\react-music\node_modules\express\lib\router\index.js:317:13)
    at E:\react学习\react-music\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\react学习\react-music\node_modules\express\lib\router\index.js:335:12)
    at next (E:\react学习\react-music\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (E:\react学习\react-music\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (E:\react学习\react-music\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\react学习\react-music\node_modules\express\lib\router\index.js:317:13)
    at E:\react学习\react-music\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\react学习\react-music\node_modules\express\lib\router\index.js:335:12)
    at next (E:\react学习\react-music\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (E:\react学习\react-music\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (E:\react学习\react-music\node_modules\express\lib\router\layer.js:95:5)

**Comment by maomao1996** [comment]
你好，可以先切换到 `old` 分支使用
